language: python

matrix:
  include:
    - name: "Python 3.8"
      python: 3.8
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.6"
      python: 3.6

script:
  - python setup.py build install
  - python -m unittest tests.unit_tests.OtomoTest.test_02_local

notifications:
  emails:
    - aokada@ncc.go.jp
  on_success: change
  on_failure: always
